import Head from "next/head";
import chat from "@/styles/Chat.module.css";
import {inter} from "@/pages/_app";
import {Avatar, AvatarGroup} from "@chakra-ui/avatar";
import {Text, Button, Icon, useDisclosure} from '@chakra-ui/react'
import {useAuthStore} from "@/services/stores/auth-store";
import {AddIcon} from "@chakra-ui/icons";
import {palette} from "@/theme/palette";
import { AiOutlineUserAdd } from 'react-icons/ai';
import {MouseEventHandler, useRef} from "react";
import {ChannelCreationModal} from "@/pages/components/channel-creation-modal";
import {useChannelStore} from "@/services/stores/channel-store";
import {channelProvider} from "@/services/providers/channel-provider";
import {authProvider} from "@/services/providers/auth-provider";
import {ChannelMemberModal} from "@/pages/components/channel-members-modal";

interface ChanelAvatarProps {
    text: string;
    onClick: MouseEventHandler<HTMLDivElement>;
}

export default function Chat() {
    const { user, setUsers } = useAuthStore();
    const { channel ,allChannels, setChannel } = useChannelStore();

    const { isOpen, onOpen, onClose } = useDisclosure();
    const { isOpen: openMember, onOpen: onOpenMember, onClose: onCloseMember } = useDisclosure();

    const initialRef = useRef(null)
    const finalRef = useRef(null)
    const initialMemberRef = useRef(null)
    const finalMemberRef = useRef(null)

    const ChanelAvatar = ({ text, onClick }: ChanelAvatarProps) => {
        return(
            <div style={{ display: 'flex', alignItems: 'center', width: '100%', marginBlock: 5 }} onClick={onClick}>
                <div style={{ width: '30%', display: 'flex', justifyContent: 'center' }}>
                    <Avatar bg='teal.500' style={{marginBlock: '5px'}} />
                </div>
                <div style={{ width: '70%', display: 'flex', paddingLeft: 30 }}>
                    <Text fontSize='sm' color='white'>{text}</Text>
                </div>
            </div>
            )
    }

    const showChannel = async (id: string) => {
        if (user && user.token) {
            const {data, check} = await channelProvider.getChannel(user?.token, id);
            if (check) {
                setChannel(data);
                console.log('Opération réussi');
            } else {
                console.error('Failed to create channel');
            }
        }
    };

    const addNewMember = async () => {
        if (user && user.token) {
            const {data, check} = await authProvider.getAllUsers(user.token);
            if (check) {
                setUsers(data);
                console.log('Opération réussi');
            } else {
                console.error('Failed to create channel');
            }
        }
        onOpenMember();
    }

    return(
        <>
            <Head>  
                <title>Chat</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${chat.main} ${inter.className}`}>
                <div className={chat.avatar}>
                    <AvatarGroup style={{ flexDirection: 'column', alignItems: 'flex-start', paddingTop: '10px' }}>
                        {allChannels.map(channel => (
                            <ChanelAvatar key={channel.id} text={channel.name} onClick={() => showChannel(channel.id)}/>
                        ))}
                        <div style={{ display: 'flex', alignItems: 'center', width: '100%', marginBlock: 5 }}>
                            <div style={{ width: '30%', display: 'flex', justifyContent: 'center' }}>
                                <Button colorScheme='teal' variant='solid' onClick={onOpen}>
                                    <Icon as={AddIcon} />
                                </Button>
                                <ChannelCreationModal
                                    initialRef={initialRef}
                                    finalRef={finalRef}
                                    isOpen={isOpen}
                                    onClose={onClose}
                                />
                            </div>
                        </div>
                    </AvatarGroup>
                </div>
                <div className={chat.container}>
                    <div style={{ width: '100%', height: 70, borderBottomWidth: '1px', borderColor: palette.primaryPurple, display: 'flex', alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end'}}>
                        <div style={{ width: '85%', justifyContent: 'center', alignItems: 'center', display: 'flex' }}>
                            <Text fontSize='lg' color='white'>{channel?.name}</Text>
                        </div>
                        <Button colorScheme='teal' variant='solid' style={{ width: 70, marginInline: 30 }} onClick={() => addNewMember()}>
                            <AiOutlineUserAdd />
                        </Button>
                        <ChannelMemberModal
                            initialRef={initialMemberRef}
                            finalRef={finalMemberRef}
                            isOpen={openMember}
                            onClose={onCloseMember}
                        />
                    </div>
                    <div style={{ width: '100%', flex: 1 }}>

                    </div>
                </div>
                <div className={chat.info}>
                    <div style={{width: '100%', display: 'flex', justifyContent: 'center', paddingBlock: 10, marginTop: 100}}>
                        <Avatar bg='teal.500' size="2xl"/>
                    </div>
                    <Text fontSize='2xl' color='white'>{user?.name}</Text>
                </div>
            </main>
        </>
    )
}