import Head from "next/head";
import chat from "@/styles/Chat.module.css";
import {inter} from "@/pages/_app";

export default function Chat() {
    return(
        <>
            <Head>
                <title>Chat</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${chat.main} ${inter.className}`}>

            </main>
        </>
    )
}