import Head from "next/head";
import chat from "@/styles/Chat.module.css";
import {inter} from "@/pages/_app";
import {Avatar, AvatarGroup} from "@chakra-ui/avatar";
import reactotron from "@/reactotron.config";

export default function Chat() {
    return(
        <>
            <Head>  
                <title>Chat</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${chat.main} ${inter.className}`}>
                <div className={chat.avatar}>
                    <AvatarGroup style={{ flexDirection: 'column', justifyContent: 'center', paddingTop: '10px' }}>
                        <Avatar bg='red.500' style={{marginInline: 'auto', marginBlock: '5px'}} />
                        <Avatar bg='teal.500' style={{marginInline: 'auto', marginBlock: '5px'}} />
                        <Avatar bg='teal.500' style={{marginInline: 'auto', marginBlock: '5px'}} />
                        <Avatar bg='teal.500' style={{marginInline: 'auto', marginBlock: '5px'}} />
                        <Avatar bg='teal.500' style={{marginInline: 'auto', marginBlock: '5px'}} />
                    </AvatarGroup>
                </div>
                <div className={chat.container}>
                    <div className={chat.discussion}>

                    </div>
                </div>
            </main>
        </>
    )
}