import Head from 'next/head'
import loginStyle from '@/styles/Login.module.css'
import {Button} from "@chakra-ui/button";
import Image from 'next/image';
import img from './logo.png';
import {useForm} from "react-hook-form";
import {inter} from "@/pages/_app";
import {palette} from "@/theme/palette";
import {useRouter} from "next/router";
import Authentication from "@/pages/Authentication";
import {useState} from "react";

export default function Login() {

    const { register, handleSubmit, formState } = useForm();
    const router = useRouter();
    const [login, setLogin] = useState(false);

    const onSubmit = (data: any) => {
        console.log(data);
        const jsonData = JSON.stringify(data);
        window.localStorage.setItem('myInformation', jsonData);
        setLogin(!login);
    };

    Authentication(router, login);

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${loginStyle.main} ${inter.className}`}>
                <div className={loginStyle.container}>
                    <form className={loginStyle.form}>
                        <div className={loginStyle.formContainer}>
                        <div className="relative z-0 w-2/3 mx-auto mb-6 group">
                            <input type="text" id="floating_name"
                                   className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                   placeholder=" " required {...register("name")}/>
                            <label htmlFor="floating_name"
                                   className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Nom
                                </label>
                        </div>
                            <div className="relative z-0 w-2/3 mx-auto mb-6 group">
                            <input type="email" id="floating_email"
                                   className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                   placeholder=" " required {...register("email")}/>
                            <label htmlFor="floating_email"
                                   className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email
                                </label>
                        </div>
                            <div className="relative z-0 w-2/3 mx-auto mb-6 group">
                            <input type="password" id="floating_password"
                                   className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                   placeholder=" " required {...register("password")}/>
                            <label htmlFor="floating_password"
                                   className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Mot de passe</label>
                        </div>
                            <div className="relative z-0 w-2/3 mx-auto mb-6 group">
                                <input type="password" id="floating_password"
                                       className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                       placeholder=" " required {...register("confirmPassword")}/>
                                <label htmlFor="floating_password"
                                       className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Confirmer</label>
                            </div>
                            <div className={loginStyle.submit}>
                            <Button
                                mt={1}
                                colorScheme='teal'
                                type='submit'
                                isLoading={formState.isSubmitting}
                                onClick={handleSubmit(onSubmit)}
                                style={{ backgroundColor: palette.primaryPurple, fontSize: '14px', color: 'white', marginBlock: 'auto', width: '40%', borderRadius: '50px', marginLeft: '30%', boxShadow: "0 0 7px 7px rgba(170, 119, 255, 0.5)"}}
                            >
                                Se connecter
                            </Button>
                            </div>
                        </div>
                    </form>
                    <div className={loginStyle.presentation}>
                        <Image src={img} alt="Logo" style={{ width: '700px', height: '400px'}}/>
                    </div>
                </div>
            </main>
        </>
    )
}
