import Head from 'next/head'
import loginStyle from '@/styles/Login.module.css'
import {Button} from "@chakra-ui/button";
import Image from 'next/image';
import img from './logo.png';
import {useForm} from "react-hook-form";
import {inter} from "@/pages/_app";
import {palette} from "@/theme/palette";
import {useRouter} from "next/router";
import {authProvider} from "@/services/providers/auth-provider";
import {CreateUser, LoginUser} from "@/services/types";
import { useAuthStore } from '@/services/stores/auth-store';
import {Text, useToast} from "@chakra-ui/react";
import * as yup from "yup";
import {yupResolver} from "@hookform/resolvers/yup";

export default function SignUp() {
    const toast = useToast();
    const formDefaultValues: CreateUser = {
        email: '',
        password: '',
        name: '',
        bio: '',
    };

    const validationSchema = yup.object().shape({
        name: yup.string().required('Ce champ est requis'),
        email: yup.string().email('Adresse Email Invalide').required('Ce champ est requis'),
    });

    const { register, handleSubmit, formState: {errors} } = useForm<CreateUser>({
        defaultValues: formDefaultValues,
        resolver: yupResolver(validationSchema)
    });
    const { setUser } = useAuthStore();
    const router = useRouter();

    const onSubmit = (infos: CreateUser) => {
        const signUp = async () => {
            const { data, authenticate } = await authProvider.signUp(infos);
            if (authenticate) {
                setUser(data);
                toast({
                    title: 'Authentifié',
                    status: 'success',
                    duration: 3000,
                    isClosable: true,
                })
                localStorage.setItem('accessToken', data.token);
                await router.push('/profile');
            } else {
                toast({
                    title: 'Erreur',
                    description: 'Veuillez vérifié vos informations',
                    status: 'error',
                    duration: 3000,
                    isClosable: true,
                })
            }
        };
        signUp();
    };

    return (
        <>
            <Head>
                <title>Sign Up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${loginStyle.main} ${inter.className}`}>
                <div className={loginStyle.container}>
                    <form className={loginStyle.form}>
                        <div className={loginStyle.formContainer}>
                            <div className="relative z-0 w-3/5 mx-auto mb-7 group">
                                <input type="text" id="floating_name"
                                       className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                       {...register("name")}/>
                                <label htmlFor="floating_email"
                                       className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">{"Nom d'Utilisateur"}
                                </label>
                                {errors.name && <Text fontSize='sm' color='red'>{errors.name?.message}</Text>}
                            </div>
                            <div className="relative z-0 w-3/5 mx-auto mb-7 group">
                            <input type="email" id="floating_email"
                                   className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                   required {...register("email")}/>
                            <label htmlFor="floating_email"
                                   className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email
                                </label>
                                {errors.email && <Text fontSize='sm' color='red'>{errors.email?.message}</Text>}
                        </div>
                            <div className="relative z-0 w-3/5 mx-auto mb-7 group">
                            <input type="password" id="floating_password"
                                   className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                   placeholder=" " required {...register("password")}/>
                            <label htmlFor="floating_password"
                                   className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Mot de passe</label>
                        </div>
                            <div className="relative z-0 w-3/5 mx-auto mb-7 group">
                                <input type="text" id="floating_email"
                                       className="block py-2.5 px-0 w-full text-sm text-gray-400 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-600 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                                       placeholder=" " required {...register("bio")}/>
                                <label htmlFor="floating_email"
                                       className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Biographie
                                </label>
                            </div>
                            <div className={loginStyle.submit}>
                            <Button
                                className="registerButton"
                                mt={1}
                                colorScheme='teal'
                                type='submit'
                                onClick={handleSubmit(onSubmit)}
                                style={{ backgroundColor: palette.primaryPurple, fontSize: '14px', color: 'white', marginBlock: 'auto', width: '40%', borderRadius: '50px', marginLeft: '30%', boxShadow: "0 0 7px 7px rgba(170, 119, 255, 0.5)"}}
                            >
                                Creer un compte
                            </Button>
                                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', marginTop: 10 }}>
                                    <Text fontSize='sm' color='white' onClick={() => router.push('/login')}>Se Connecter ?</Text>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div className={loginStyle.presentation}>
                        <Image src={img} alt="Logo" style={{ width: '700px', height: '400px'}}/>
                    </div>
                </div>
            </main>
        </>
    )
}
